"use client";

import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";
import { useState } from "react";

const shell: React.CSSProperties = { background: "#080808", color: "white", minHeight: "100vh", overflow: "hidden" };
const card: React.CSSProperties = { background: "rgba(255,255,255,.035)", border: "1px solid rgba(255,255,255,.09)", borderRadius: 18, boxShadow: "0 24px 70px rgba(0,0,0,.25)" };

function Logo() { return <Link href="/" style={{ display: "flex", alignItems: "center", textDecoration: "none" }}><span style={{ fontSize: "22px", fontWeight: 800, background: "linear-gradient(135deg, #a855f7, #3b82f6)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>CoSkill</span></Link>; }

function MarqueeRow({ label, items, reverse = false }: { label: string; items: string[]; reverse?: boolean }) {
  const content = [...items, ...items];
  return <div className="integration-row"><span className="integration-label">{label}</span><div className="integration-marquee"><div className={`integration-track${reverse ? " reverse" : ""}`}>{content.map((item, index) => <span key={`${item}-${index}`} className="integration-pill">{item}</span>)}</div></div></div>;
}

function DashboardMockup() {
  const tasks = [["01", "Model checkout state", "done"], ["02", "Ship payment webhook", "active"], ["03", "Write edge-case tests", "queued"]];
  return <div className="landing-mockup landing-code-mockup" style={{ width: "min(100%, 860px)", margin: "58px auto 0", transform: "perspective(1200px) rotateX(4deg)", overflow: "hidden", border: "1px solid #30363d", borderRadius: 14, background: "#0d1117", boxShadow: "0 34px 100px rgba(0,0,0,.55), 0 0 70px rgba(47,129,247,.12)", fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" }}>
    <div style={{ display: "flex", alignItems: "center", gap: 7, padding: "12px 15px", borderBottom: "1px solid #30363d", background: "#161b22" }}>{["#ff7b72", "#d29922", "#3fb950"].map((color) => <i key={color} style={{ width: 9, height: 9, borderRadius: "50%", background: color }} />)}<span style={{ marginLeft: 8, color: "#8b949e", fontSize: 11 }}>coskill / workspace / ai-planner</span><span className="landing-code-pulse" style={{ marginLeft: "auto", color: "#3fb950", fontSize: 10 }}>● LIVE</span></div>
    <div className="landing-code-layout" style={{ display: "grid", gridTemplateColumns: "172px minmax(0, 1fr)", minHeight: 370 }}>
      <aside style={{ padding: "18px 14px", borderRight: "1px solid #30363d", background: "#161b22", color: "#8b949e", fontSize: 11 }}><b style={{ display: "block", marginBottom: 20, color: "#e6edf3", fontSize: 12, letterSpacing: ".08em" }}>COSKILL<span style={{ color: "#3fb950" }}>_</span></b><p style={{ margin: "0 0 8px", color: "#484f58", fontSize: 9, letterSpacing: ".12em" }}>PROJECT FILES</p>{["overview.ts", "tasks.ai", "evidence.log", "performance.json"].map((file, index) => <div key={file} style={{ padding: "7px 8px", marginBottom: 2, borderRadius: 5, background: index === 1 ? "rgba(47,129,247,.16)" : "transparent", color: index === 1 ? "#79c0ff" : undefined }}>⌘&nbsp; {file}</div>)}<div style={{ marginTop: 28, padding: 10, border: "1px solid #30363d", borderRadius: 7, background: "#0d1117" }}><span style={{ display: "block", color: "#8b949e", fontSize: 9 }}>SYNC STATUS</span><b style={{ display: "block", marginTop: 5, color: "#3fb950", fontSize: 11 }}>✓ all systems ready</b></div></aside>
      <div style={{ minWidth: 0, padding: "20px 22px", background: "linear-gradient(135deg,#0d1117 25%,#101923 100%)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", gap: 14, alignItems: "flex-start", marginBottom: 18 }}><div><p style={{ margin: 0, color: "#3fb950", fontSize: 11 }}><span style={{ color: "#58a6ff" }}>~</span> $ coskill decompose <span className="landing-terminal-command">"Realtime Checkout"</span><i className="landing-terminal-cursor" /></p><h3 style={{ margin: "12px 0 0", color: "#e6edf3", fontSize: 19, letterSpacing: "-.04em", fontFamily: "inherit" }}>Realtime Checkout</h3><p style={{ margin: "5px 0 0", color: "#8b949e", fontSize: 11 }}>PROJECT_042 · AI decomposition complete</p></div><span style={{ padding: "6px 8px", borderRadius: 5, border: "1px solid rgba(63,185,80,.4)", background: "rgba(63,185,80,.09)", color: "#3fb950", fontSize: 10 }}>READY_TO_BUILD</span></div>
        <div className="landing-code-stats" style={{ display: "grid", gridTemplateColumns: "1.1fr .9fr", gap: 10, marginBottom: 12 }}><div style={{ padding: 13, border: "1px solid #30363d", borderRadius: 8, background: "rgba(22,27,34,.85)" }}><span style={{ color: "#8b949e", fontSize: 10 }}>CURRENT XP</span><div style={{ display: "flex", alignItems: "end", gap: 7, marginTop: 6 }}><b style={{ color: "#3fb950", fontSize: 25, lineHeight: 1 }}>2,840</b><span style={{ marginBottom: 3, color: "#8b949e", fontSize: 10 }}>/ 3,200 XP</span></div><div style={{ height: 5, marginTop: 9, overflow: "hidden", borderRadius: 99, background: "#21262d" }}><i style={{ display: "block", width: "88%", height: "100%", borderRadius: 99, background: "linear-gradient(90deg,#238636,#3fb950)" }} /></div><span style={{ display: "block", marginTop: 7, color: "#79c0ff", fontSize: 10 }}>LEVEL 08 · Builder</span></div><div style={{ padding: 13, border: "1px solid #30363d", borderRadius: 8, background: "rgba(22,27,34,.85)" }}><span style={{ color: "#8b949e", fontSize: 10 }}>PERFORMANCE_SCORE</span><div style={{ display: "flex", alignItems: "baseline", gap: 7, marginTop: 6 }}><b style={{ color: "#79c0ff", fontSize: 27, lineHeight: 1 }}>86</b><span style={{ color: "#8b949e", fontSize: 10 }}>/ 100</span></div><span style={{ display: "inline-block", marginTop: 10, color: "#3fb950", fontSize: 10 }}>↑ 12% this sprint</span></div></div>
        <div style={{ border: "1px solid #30363d", borderRadius: 8, overflow: "hidden", background: "#0d1117" }}><div style={{ display: "flex", justifyContent: "space-between", padding: "10px 12px", borderBottom: "1px solid #30363d", color: "#8b949e", fontSize: 10 }}><span><b style={{ color: "#e6edf3" }}>AI_DECOMPOSED_TASKS</b> · 03 generated</span><span style={{ color: "#3fb950" }}>confidence 96%</span></div>{tasks.map(([number, task, state], index) => <div key={number} className={state === "active" ? "landing-active-task" : ""} style={{ display: "grid", gridTemplateColumns: "27px 1fr auto", gap: 8, alignItems: "center", padding: "10px 12px", borderTop: index ? "1px solid rgba(48,54,61,.65)" : 0, color: "#c9d1d9", fontSize: 11 }}><span style={{ color: "#484f58" }}>{number}</span><span><i style={{ marginRight: 7, color: state === "done" ? "#3fb950" : state === "active" ? "#58a6ff" : "#8b949e", fontStyle: "normal" }}>{state === "done" ? "✓" : state === "active" ? "◌" : "○"}</i>{task}</span><span style={{ color: state === "done" ? "#3fb950" : state === "active" ? "#79c0ff" : "#8b949e", fontSize: 9 }}>{state.toUpperCase()}</span></div>)}</div>
      </div>
    </div>
  </div>;
}

export default function LandingPage() {
  const { user } = useAuth();
  const primary = user ? "/dashboard" : "/register";
  const [menuOpen, setMenuOpen] = useState(false);
  return <main style={shell}>
    <div aria-hidden style={{ position: "absolute", inset: 0, pointerEvents: "none", background: "radial-gradient(circle at 20% 5%, rgba(168,85,247,.2), transparent 28%), radial-gradient(circle at 82% 25%, rgba(59,130,246,.16), transparent 26%)" }} />
    <nav style={{ position: "relative", zIndex: 30, display: "flex", alignItems: "center", justifyContent: "space-between", maxWidth: 1160, margin: "0 auto", padding: "14px 24px" }}><Logo /><div className="landing-desktop-nav" style={{ display: "flex", gap: 22, alignItems: "center" }}><a href="#features" style={{ color: "rgba(255,255,255,.6)", textDecoration: "none", fontSize: 14 }}>Features</a><a href="#how-it-works" style={{ color: "rgba(255,255,255,.6)", textDecoration: "none", fontSize: 14 }}>How it works</a>{!user && <Link href="/login" style={{ color: "rgba(255,255,255,.62)", textDecoration: "none", fontSize: 14 }}>Log in</Link>}<Link href={primary} style={{ padding: "9px 14px", borderRadius: 8, background: "linear-gradient(135deg,#a855f7,#3b82f6)", color: "white", fontSize: 14, fontWeight: 700, textDecoration: "none" }}>{user ? "Dashboard" : "Get started"}</Link></div><button className="landing-menu-button" onClick={() => setMenuOpen(true)} aria-label="Open navigation menu" style={{ display: "none", width: 42, height: 42, borderRadius: 9, background: "rgba(255,255,255,.05)", border: "1px solid rgba(255,255,255,.12)", color: "white", cursor: "pointer" }}><span style={{ display: "grid", gap: 4 }}><i style={{ width: 18, height: 2, background: "currentColor" }} /><i style={{ width: 18, height: 2, background: "currentColor" }} /><i style={{ width: 18, height: 2, background: "currentColor" }} /></span></button></nav>
    {menuOpen && <div role="dialog" aria-modal="true" style={{ position: "fixed", inset: 0, zIndex: 50, background: "rgba(0,0,0,.64)", backdropFilter: "blur(5px)" }} onClick={() => setMenuOpen(false)}><aside onClick={(e) => e.stopPropagation()} style={{ marginLeft: "auto", width: "min(82vw, 340px)", height: "100%", padding: 24, background: "#121212", borderLeft: "1px solid rgba(255,255,255,.1)", boxShadow: "-24px 0 70px rgba(0,0,0,.4)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 40 }}><Logo /><button onClick={() => setMenuOpen(false)} style={{ border: 0, background: "transparent", color: "rgba(255,255,255,.65)", fontSize: 25, cursor: "pointer" }}>×</button></div><div style={{ display: "grid", gap: 8 }}><a href="#features" onClick={() => setMenuOpen(false)} style={{ padding: "13px 12px", color: "white", textDecoration: "none", borderRadius: 9, background: "rgba(255,255,255,.04)" }}>Features</a><a href="#how-it-works" onClick={() => setMenuOpen(false)} style={{ padding: "13px 12px", color: "white", textDecoration: "none", borderRadius: 9, background: "rgba(255,255,255,.04)" }}>How it works</a><Link href={primary} onClick={() => setMenuOpen(false)} style={{ marginTop: 8, padding: "13px 12px", color: "white", textAlign: "center", fontWeight: 700, textDecoration: "none", borderRadius: 9, background: "linear-gradient(135deg,#a855f7,#3b82f6)" }}>Get started</Link></div></aside></div>}
    <section style={{ position: "relative", zIndex: 1, maxWidth: 1160, margin: "0 auto", padding: "78px 24px 90px", textAlign: "center" }}><span style={{ display: "inline-block", padding: "6px 11px", borderRadius: 99, background: "rgba(168,85,247,.11)", border: "1px solid rgba(168,85,247,.25)", color: "#d8b4fe", fontSize: 12, fontWeight: 700 }}>WORK, VERIFIED</span><h1 style={{ maxWidth: 820, margin: "20px auto 17px", fontSize: "clamp(44px,7vw,78px)", lineHeight: .98, letterSpacing: "-.06em" }}>Your work deserves more than a <span className="gradient-text">static CV.</span></h1><p style={{ maxWidth: 570, margin: "0 auto", color: "rgba(255,255,255,.52)", fontSize: 17, lineHeight: 1.6 }}>Turn real projects into an evidence-backed skill profile. CoSkill plans the work, tracks the effort, and makes your progress shareable.</p><div style={{ display: "flex", justifyContent: "center", gap: 11, marginTop: 30, flexWrap: "wrap" }}><Link href={primary} style={{ padding: "13px 21px", borderRadius: 9, background: "linear-gradient(135deg,#a855f7,#3b82f6)", color: "white", fontWeight: 700, textDecoration: "none" }}>Build your proof of work →</Link><a href="#how-it-works" style={{ padding: "13px 21px", borderRadius: 9, border: "1px solid rgba(255,255,255,.12)", color: "rgba(255,255,255,.75)", textDecoration: "none" }}>See how it works</a></div><DashboardMockup /></section>
    <section id="how-it-works" style={{ position: "relative", zIndex: 1, maxWidth: 1060, margin: "0 auto", padding: "75px 24px" }}><div style={{ textAlign: "center", marginBottom: 42 }}><p style={{ color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>SEE HOW IT WORKS</p><h2 style={{ margin: "8px 0", fontSize: "clamp(29px,4vw,46px)", letterSpacing: "-.05em" }}>From goal to proof — in four moves.</h2></div><div className="landing-grid-4" style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14 }}>{[["01", "Create a project", "Describe the goal, not the busywork."], ["02", "AI breaks it down", "Get focused tasks, estimates, and skills."], ["03", "Track & score", "Build a performance record as you work."], ["04", "Share your CV", "Send a profile backed by real outcomes."]].map(([number, title, body]) => <article key={number} style={{ ...card, padding: 19, minHeight: 180 }}><span style={{ color: "#c084fc", fontWeight: 800, fontSize: 13 }}>{number}</span><div style={{ width: 34, height: 34, display: "grid", placeItems: "center", margin: "15px 0", borderRadius: 9, background: "linear-gradient(135deg,rgba(168,85,247,.25),rgba(59,130,246,.2))" }}>✦</div><h3 style={{ margin: 0, fontSize: 15 }}>{title}</h3><p style={{ margin: "7px 0 0", color: "rgba(255,255,255,.43)", fontSize: 13, lineHeight: 1.55 }}>{body}</p></article>)}</div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 1060, margin: "0 auto", padding: "25px 24px 75px" }}><div className="landing-proof" style={{ display: "grid", gridTemplateColumns: "1.05fr .95fr", gap: 16 }}><div style={{ ...card, padding: 30, background: "linear-gradient(135deg,rgba(168,85,247,.16),rgba(59,130,246,.08))" }}><p style={{ margin: 0, color: "#d8b4fe", fontWeight: 800, fontSize: 12, letterSpacing: ".1em" }}>BUILT FOR REAL PROGRESS</p><blockquote style={{ margin: "20px 0 17px", fontSize: 22, lineHeight: 1.35, letterSpacing: "-.03em" }}>“CoSkill made my portfolio feel like a living record, not a list of claims.”</blockquote><p style={{ margin: 0, color: "rgba(255,255,255,.5)", fontSize: 13 }}>— Product builder, early CoSkill community</p></div><div style={{ ...card, padding: 30, display: "grid", alignContent: "center", gap: 14 }}><div style={{ display: "flex", gap: 8 }}>{["M", "A", "S", "R"].map((name, i) => <span key={name} style={{ width: 32, height: 32, display: "grid", placeItems: "center", marginLeft: i ? -11 : 0, borderRadius: "50%", background: ["#a855f7", "#3b82f6", "#14b8a6", "#f59e0b"][i], border: "2px solid #151515", fontSize: 11, fontWeight: 800 }}>{name}</span>)}</div><b style={{ fontSize: 18 }}>A clearer story than a bullet list.</b><span style={{ color: "rgba(255,255,255,.43)", fontSize: 13, lineHeight: 1.5 }}>Projects, task evidence, and measurable skills in one shareable profile.</span></div></div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 900, margin: "0 auto", padding: "25px 24px 82px" }}><div style={{ textAlign: "center", marginBottom: 25 }}><p style={{ color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>WHY COSKILL</p><h2 style={{ margin: "8px 0", fontSize: 32, letterSpacing: "-.04em" }}>Show what you can do.</h2></div><div style={{ overflow: "hidden", ...card }}><table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}><thead><tr style={{ background: "rgba(255,255,255,.035)", textAlign: "left" }}><th style={{ padding: 14 }}> </th><th style={{ padding: 14, color: "#d8b4fe" }}>CoSkill</th><th style={{ padding: 14, color: "rgba(255,255,255,.55)" }}>Traditional CV</th><th style={{ padding: 14, color: "rgba(255,255,255,.55)" }}>LinkedIn</th></tr></thead><tbody>{[["Evidence from real work", "✓", "—", "Sometimes"], ["Live skill scores", "✓", "—", "—"], ["AI project planning", "✓", "—", "—"], ["Shareable profile", "✓", "PDF", "✓"]].map((row) => <tr key={row[0]} style={{ borderTop: "1px solid rgba(255,255,255,.07)" }}>{row.map((cell, index) => <td key={`${cell}-${index}`} style={{ padding: 14, color: index === 1 ? "#86efac" : index ? "rgba(255,255,255,.56)" : "rgba(255,255,255,.85)", fontWeight: index === 0 ? 600 : 400 }}>{cell}</td>)}</tr>)}</tbody></table></div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 1060, margin: "0 auto", padding: "0 24px 74px", textAlign: "center" }}><p style={{ color: "rgba(255,255,255,.38)", fontSize: 12, fontWeight: 700, letterSpacing: ".12em" }}>TRUSTED BY BUILDERS AT</p><div className="landing-trusted" style={{ display: "flex", justifyContent: "space-between", gap: 18, marginTop: 25, color: "rgba(255,255,255,.52)", fontSize: 20, fontWeight: 800, letterSpacing: "-.04em" }}>{["NORTHSTAR", "vertex", "LUMA", "orbit", "FOUNDRY"].map((company) => <span key={company}>{company}</span>)}</div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 820, margin: "0 auto", padding: "0 24px 82px" }}><div style={{ textAlign: "center", marginBottom: 25 }}><p style={{ color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>FAQ</p><h2 style={{ margin: "8px 0", fontSize: 32, letterSpacing: "-.04em" }}>Questions, answered.</h2></div><div style={{ display: "grid", gap: 9 }}>{[["What is CoSkill?", "CoSkill turns projects and completed tasks into a living, shareable record of your skills."], ["How does the performance score work?", "Scores use task difficulty and completion timing, then aggregate into an easy-to-read profile."], ["Can I share my profile?", "Yes. Each user has a public profile link and can export a print-ready performance CV."], ["Is CoSkill only for developers?", "No. The project workflow works for any role that wants to demonstrate skills through real work."]].map(([question, answer]) => <details key={question} style={{ ...card, padding: "16px 18px", cursor: "pointer" }}><summary style={{ fontWeight: 700, listStyle: "none" }}>{question}<span style={{ float: "right", color: "#c084fc" }}>+</span></summary><p style={{ margin: "12px 0 0", color: "rgba(255,255,255,.47)", fontSize: 14, lineHeight: 1.55 }}>{answer}</p></details>)}</div></section>
    <section style={{ position: "relative", zIndex: 1, margin: 0, padding: "68px 24px", textAlign: "center", background: "radial-gradient(circle at top,rgba(168,85,247,.32),rgba(35,22,69,.78) 45%,#101014 100%)", borderTop: "1px solid rgba(168,85,247,.25)" }}><h2 style={{ maxWidth: 600, margin: "0 auto", fontSize: "clamp(32px,5vw,54px)", letterSpacing: "-.055em" }}>Make your next project count.</h2><p style={{ color: "rgba(255,255,255,.58)", margin: "15px auto 26px", maxWidth: 450 }}>Build a work record you&apos;ll be proud to share.</p><Link href={primary} style={{ display: "inline-block", padding: "13px 22px", borderRadius: 9, background: "white", color: "#1a102c", fontWeight: 800, textDecoration: "none" }}>Get started with CoSkill →</Link></section>
    <section style={{ position: "relative", zIndex: 1, padding: "72px 0", overflow: "hidden", borderTop: "1px solid rgba(255,255,255,.07)", borderBottom: "1px solid rgba(255,255,255,.07)" }}><div style={{ textAlign: "center", padding: "0 24px", marginBottom: 31 }}><p style={{ margin: 0, color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>INTEGRATIONS COMING SOON</p><h2 style={{ margin: "9px 0 0", fontSize: "clamp(27px,4vw,40px)", letterSpacing: "-.045em" }}>Connect your entire work ecosystem</h2></div><div style={{ display: "grid", gap: 17 }}><MarqueeRow label="Work & Freelance" items={["GitHub", "GitLab", "Upwork", "Fiverr", "Toptal", "Freelancer", "Jira", "Notion", "Asana", "Slack"]} /><MarqueeRow label="Education" reverse items={["Coursera", "edX", "Udemy", "Codecademy", "Khan Academy", "Pluralsight", "LinkedIn Learning"]} /><MarqueeRow label="Apps & Platforms" items={["App Store", "Google Play", "Chrome", "Apple", "Google", "Microsoft"]} /></div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 1060, margin: "0 auto", padding: "86px 24px" }}><div style={{ textAlign: "center", marginBottom: 42 }}><p style={{ margin: 0, color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>COMING SOON</p><h2 style={{ margin: "9px 0 7px", fontSize: "clamp(30px,4vw,44px)", letterSpacing: "-.05em" }}>Build Your Professional Network</h2><p style={{ margin: 0, color: "rgba(255,255,255,.45)", fontSize: 15 }}>Connect around meaningful work, not empty noise.</p></div><div className="community-feature-grid" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "36px 28px" }}>{[["👥", "Follow System", "Follow top performers, get inspired by their work."], ["👫", "Teams & Groups", "Create teams, collaborate on shared projects."], ["📢", "Work Feed", "Share your wins, celebrate milestones publicly."], ["❓", "Community Q&A", "Ask questions, get answers from peers."], ["🌍", "Global Talent Discovery", "Be found by companies worldwide."]].map(([icon, title, description]) => <div key={title} style={{ textAlign: "center" }}><div style={{ fontSize: 38, lineHeight: 1, marginBottom: 14 }}>{icon}</div><h3 style={{ margin: 0, fontSize: 16, letterSpacing: "-.02em" }}>{title}</h3><p style={{ margin: "7px auto 0", maxWidth: 230, color: "rgba(255,255,255,.43)", fontSize: 13, lineHeight: 1.55 }}>{description}</p></div>)}</div></section>
    <footer style={{ position: "relative", zIndex: 1, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, padding: "25px max(24px, calc((100% - 1112px) / 2))", background: "#080808", borderTop: "1px solid rgba(255,255,255,.07)", color: "rgba(255,255,255,.38)", fontSize: 13 }}><Logo /><div style={{ display: "flex", gap: 18 }}><a href="#about" style={{ color: "inherit", textDecoration: "none" }}>About</a><a href="#privacy" style={{ color: "inherit", textDecoration: "none" }}>Privacy</a><a href="https://github.com/Meltechx/CoSkill" target="_blank" rel="noreferrer" style={{ color: "inherit", textDecoration: "none" }}>GitHub</a></div></footer>
    <style jsx>{`
      @keyframes terminal-cursor { 0%, 46% { opacity: 1; } 47%, 100% { opacity: 0; } }
      @keyframes terminal-live-pulse { 0%, 100% { opacity: .65; text-shadow: none; } 50% { opacity: 1; text-shadow: 0 0 12px #3fb950; } }
      @keyframes active-task-glow { 0%, 100% { background: transparent; } 50% { background: rgba(47,129,247,.1); } }
      .landing-terminal-cursor { display: inline-block; width: 6px; height: 13px; margin-left: 4px; vertical-align: -2px; background: #3fb950; animation: terminal-cursor 1s steps(1) infinite; }
      .landing-code-pulse { animation: terminal-live-pulse 2.2s ease-in-out infinite; }
      .landing-active-task { animation: active-task-glow 2.8s ease-in-out infinite; }
      @media (prefers-reduced-motion: reduce) { .landing-terminal-cursor, .landing-code-pulse, .landing-active-task { animation: none; } }
      @media (max-width:700px){.landing-mockup{transform:none!important}.landing-grid-4{grid-template-columns:1fr 1fr!important}.landing-proof{grid-template-columns:1fr!important}.landing-desktop-nav{display:none!important}.landing-menu-button{display:grid!important;place-items:center}.landing-trusted{flex-wrap:wrap;justify-content:center!important}}
      @media (max-width:520px){.landing-grid-4{grid-template-columns:1fr!important}.landing-code-layout{grid-template-columns:1fr!important}.landing-code-layout aside{display:none}.landing-code-stats{grid-template-columns:1fr!important}.landing-code-mockup{font-size:92%}}
    `}</style>
  </main>;
}
