"use client";

import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";

const shell: React.CSSProperties = { background: "#080808", color: "white", minHeight: "100vh", overflow: "hidden" };
const card: React.CSSProperties = { background: "rgba(255,255,255,.035)", border: "1px solid rgba(255,255,255,.09)", borderRadius: 18, boxShadow: "0 24px 70px rgba(0,0,0,.25)" };

function Logo() { return <Link href="/" style={{ display: "flex", alignItems: "center", gap: 8, color: "white", fontWeight: 800, fontSize: 17, textDecoration: "none" }}><span style={{ width: 29, height: 29, display: "grid", placeItems: "center", borderRadius: 8, background: "linear-gradient(135deg,#a855f7,#3b82f6)", fontSize: 13 }}>C</span>CoSkill</Link>; }

function DashboardMockup() {
  const tasks = [["Ship auth flow", "Done", 100], ["Build API endpoints", "In progress", 70], ["Review performance", "Today", 42]];
  return <div className="landing-mockup" style={{ ...card, padding: 14, width: "min(100%, 820px)", margin: "58px auto 0", transform: "perspective(1200px) rotateX(4deg)" }}>
    <div style={{ display: "flex", gap: 6, padding: "3px 2px 13px" }}>{["#fb7185", "#fbbf24", "#4ade80"].map((color) => <i key={color} style={{ width: 8, height: 8, borderRadius: "50%", background: color }} />)}<span style={{ marginLeft: 7, color: "rgba(255,255,255,.3)", fontSize: 11 }}>app.coskill.dev / dashboard</span></div>
    <div style={{ display: "grid", gridTemplateColumns: "130px 1fr", minHeight: 310, borderRadius: 11, overflow: "hidden", background: "#101010" }}>
      <aside style={{ padding: 16, borderRight: "1px solid rgba(255,255,255,.07)", color: "rgba(255,255,255,.38)", fontSize: 11 }}><b style={{ display: "block", color: "#c084fc", marginBottom: 20 }}>COSKILL</b>{["Overview", "Projects", "Performance", "Profile"].map((item, index) => <div key={item} style={{ padding: "8px 7px", marginBottom: 3, borderRadius: 6, background: index === 0 ? "rgba(168,85,247,.15)" : "transparent", color: index === 0 ? "white" : undefined }}>{item}</div>)}</aside>
      <div style={{ padding: "20px 22px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 17 }}><div><b style={{ fontSize: 17 }}>Good work, Maya</b><p style={{ margin: "4px 0", color: "rgba(255,255,255,.4)", fontSize: 11 }}>Your performance is trending up.</p></div><span style={{ padding: "7px 10px", borderRadius: 7, background: "linear-gradient(135deg,#a855f7,#3b82f6)", fontSize: 11 }}>+ New project</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 9, marginBottom: 15 }}>{[["84", "Performance"], ["12", "Tasks done"], ["4", "Skills tracked"]].map(([value, label]) => <div key={label} style={{ padding: 11, borderRadius: 9, background: "rgba(255,255,255,.04)", border: "1px solid rgba(255,255,255,.06)" }}><b style={{ display: "block", fontSize: 19 }}>{value}</b><small style={{ color: "rgba(255,255,255,.38)" }}>{label}</small></div>)}</div><div style={{ padding: 13, borderRadius: 10, background: "rgba(255,255,255,.03)", border: "1px solid rgba(255,255,255,.06)" }}><b style={{ fontSize: 12 }}>Product launch</b>{tasks.map(([label, state, progress]) => <div key={String(label)} style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 11, fontSize: 11 }}><i style={{ width: 9, height: 9, borderRadius: 3, background: Number(progress) === 100 ? "#4ade80" : "#a855f7" }} /><span style={{ flex: 1, color: "rgba(255,255,255,.72)" }}>{label}</span><span style={{ color: "rgba(255,255,255,.38)" }}>{state}</span><span style={{ width: 45, height: 4, borderRadius: 99, background: "rgba(255,255,255,.1)" }}><i style={{ display: "block", width: `${progress}%`, height: "100%", borderRadius: 99, background: "linear-gradient(90deg,#a855f7,#3b82f6)" }} /></span></div>)}</div></div>
    </div>
  </div>;
}

export default function LandingPage() {
  const { user } = useAuth();
  const primary = user ? "/dashboard" : "/register";
  return <main style={shell}>
    <div aria-hidden style={{ position: "absolute", inset: 0, pointerEvents: "none", background: "radial-gradient(circle at 20% 5%, rgba(168,85,247,.2), transparent 28%), radial-gradient(circle at 82% 25%, rgba(59,130,246,.16), transparent 26%)" }} />
    <nav style={{ position: "relative", zIndex: 2, display: "flex", alignItems: "center", justifyContent: "space-between", maxWidth: 1160, margin: "0 auto", padding: "20px 24px" }}><Logo /><div style={{ display: "flex", gap: 10, alignItems: "center" }}>{!user && <Link href="/login" style={{ color: "rgba(255,255,255,.62)", textDecoration: "none", fontSize: 14 }}>Log in</Link>}<Link href={primary} style={{ padding: "9px 14px", borderRadius: 8, background: "linear-gradient(135deg,#a855f7,#3b82f6)", color: "white", fontSize: 14, fontWeight: 700, textDecoration: "none" }}>{user ? "Dashboard" : "Start free"}</Link></div></nav>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 1160, margin: "0 auto", padding: "78px 24px 90px", textAlign: "center" }}><span style={{ display: "inline-block", padding: "6px 11px", borderRadius: 99, background: "rgba(168,85,247,.11)", border: "1px solid rgba(168,85,247,.25)", color: "#d8b4fe", fontSize: 12, fontWeight: 700 }}>WORK, VERIFIED</span><h1 style={{ maxWidth: 820, margin: "20px auto 17px", fontSize: "clamp(44px,7vw,78px)", lineHeight: .98, letterSpacing: "-.06em" }}>Your work deserves more than a <span className="gradient-text">static CV.</span></h1><p style={{ maxWidth: 570, margin: "0 auto", color: "rgba(255,255,255,.52)", fontSize: 17, lineHeight: 1.6 }}>Turn real projects into an evidence-backed skill profile. CoSkill plans the work, tracks the effort, and makes your progress shareable.</p><div style={{ display: "flex", justifyContent: "center", gap: 11, marginTop: 30, flexWrap: "wrap" }}><Link href={primary} style={{ padding: "13px 21px", borderRadius: 9, background: "linear-gradient(135deg,#a855f7,#3b82f6)", color: "white", fontWeight: 700, textDecoration: "none" }}>Build your proof of work →</Link><a href="#how-it-works" style={{ padding: "13px 21px", borderRadius: 9, border: "1px solid rgba(255,255,255,.12)", color: "rgba(255,255,255,.75)", textDecoration: "none" }}>See how it works</a></div><DashboardMockup /></section>
    <section id="how-it-works" style={{ position: "relative", zIndex: 1, maxWidth: 1060, margin: "0 auto", padding: "75px 24px" }}><div style={{ textAlign: "center", marginBottom: 42 }}><p style={{ color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>SEE HOW IT WORKS</p><h2 style={{ margin: "8px 0", fontSize: "clamp(29px,4vw,46px)", letterSpacing: "-.05em" }}>From goal to proof — in four moves.</h2></div><div className="landing-grid-4" style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14 }}>{[["01", "Create a project", "Describe the goal, not the busywork."], ["02", "AI breaks it down", "Get focused tasks, estimates, and skills."], ["03", "Track & score", "Build a performance record as you work."], ["04", "Share your CV", "Send a profile backed by real outcomes."]].map(([number, title, body]) => <article key={number} style={{ ...card, padding: 19, minHeight: 180 }}><span style={{ color: "#c084fc", fontWeight: 800, fontSize: 13 }}>{number}</span><div style={{ width: 34, height: 34, display: "grid", placeItems: "center", margin: "15px 0", borderRadius: 9, background: "linear-gradient(135deg,rgba(168,85,247,.25),rgba(59,130,246,.2))" }}>✦</div><h3 style={{ margin: 0, fontSize: 15 }}>{title}</h3><p style={{ margin: "7px 0 0", color: "rgba(255,255,255,.43)", fontSize: 13, lineHeight: 1.55 }}>{body}</p></article>)}</div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 1060, margin: "0 auto", padding: "25px 24px 75px" }}><div className="landing-proof" style={{ display: "grid", gridTemplateColumns: "1.05fr .95fr", gap: 16 }}><div style={{ ...card, padding: 30, background: "linear-gradient(135deg,rgba(168,85,247,.16),rgba(59,130,246,.08))" }}><p style={{ margin: 0, color: "#d8b4fe", fontWeight: 800, fontSize: 12, letterSpacing: ".1em" }}>BUILT FOR REAL PROGRESS</p><blockquote style={{ margin: "20px 0 17px", fontSize: 22, lineHeight: 1.35, letterSpacing: "-.03em" }}>“CoSkill made my portfolio feel like a living record, not a list of claims.”</blockquote><p style={{ margin: 0, color: "rgba(255,255,255,.5)", fontSize: 13 }}>— Product builder, early CoSkill community</p></div><div style={{ ...card, padding: 30, display: "grid", alignContent: "center", gap: 14 }}><div style={{ display: "flex", gap: 8 }}>{["M", "A", "S", "R"].map((name, i) => <span key={name} style={{ width: 32, height: 32, display: "grid", placeItems: "center", marginLeft: i ? -11 : 0, borderRadius: "50%", background: ["#a855f7", "#3b82f6", "#14b8a6", "#f59e0b"][i], border: "2px solid #151515", fontSize: 11, fontWeight: 800 }}>{name}</span>)}</div><b style={{ fontSize: 18 }}>A clearer story than a bullet list.</b><span style={{ color: "rgba(255,255,255,.43)", fontSize: 13, lineHeight: 1.5 }}>Projects, task evidence, and measurable skills in one shareable profile.</span></div></div></section>
    <section style={{ position: "relative", zIndex: 1, maxWidth: 900, margin: "0 auto", padding: "25px 24px 82px" }}><div style={{ textAlign: "center", marginBottom: 25 }}><p style={{ color: "#c084fc", fontSize: 12, fontWeight: 800, letterSpacing: ".12em" }}>WHY COSKILL</p><h2 style={{ margin: "8px 0", fontSize: 32, letterSpacing: "-.04em" }}>Show what you can do.</h2></div><div style={{ overflow: "hidden", ...card }}><table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}><thead><tr style={{ background: "rgba(255,255,255,.035)", textAlign: "left" }}><th style={{ padding: 14 }}> </th><th style={{ padding: 14, color: "#d8b4fe" }}>CoSkill</th><th style={{ padding: 14, color: "rgba(255,255,255,.55)" }}>Traditional CV</th><th style={{ padding: 14, color: "rgba(255,255,255,.55)" }}>LinkedIn</th></tr></thead><tbody>{[["Evidence from real work", "✓", "—", "Sometimes"], ["Live skill scores", "✓", "—", "—"], ["AI project planning", "✓", "—", "—"], ["Shareable profile", "✓", "PDF", "✓"]].map((row) => <tr key={row[0]} style={{ borderTop: "1px solid rgba(255,255,255,.07)" }}>{row.map((cell, index) => <td key={`${cell}-${index}`} style={{ padding: 14, color: index === 1 ? "#86efac" : index ? "rgba(255,255,255,.56)" : "rgba(255,255,255,.85)", fontWeight: index === 0 ? 600 : 400 }}>{cell}</td>)}</tr>)}</tbody></table></div></section>
    <section style={{ position: "relative", zIndex: 1, margin: 0, padding: "68px 24px", textAlign: "center", background: "radial-gradient(circle at top,rgba(168,85,247,.32),rgba(35,22,69,.78) 45%,#101014 100%)", borderTop: "1px solid rgba(168,85,247,.25)" }}><h2 style={{ maxWidth: 600, margin: "0 auto", fontSize: "clamp(32px,5vw,54px)", letterSpacing: "-.055em" }}>Make your next project count.</h2><p style={{ color: "rgba(255,255,255,.58)", margin: "15px auto 26px", maxWidth: 450 }}>Build a work record you&apos;ll be proud to share.</p><Link href={primary} style={{ display: "inline-block", padding: "13px 22px", borderRadius: 9, background: "white", color: "#1a102c", fontWeight: 800, textDecoration: "none" }}>Get started with CoSkill →</Link></section>
    <style jsx>{`@media (max-width:700px){.landing-mockup{transform:none!important}.landing-grid-4{grid-template-columns:1fr 1fr!important}.landing-proof{grid-template-columns:1fr!important}}@media (max-width:520px){.landing-grid-4{grid-template-columns:1fr!important}.landing-mockup aside{display:none}.landing-mockup>div{grid-template-columns:1fr!important}}`}</style>
  </main>;
}
