"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { getHackathon } from "@/lib/hackathons";

export default function HackathonDetailPage() {
  const params = useParams<{ id: string }>();
  const hackathon = getHackathon(params.id);
  const [matchingOpen, setMatchingOpen] = useState(false);
  if (!hackathon) return <div className="github-dashboard" style={{ color: "#e6edf3" }}><h1>Hackathon not found</h1><Link href="/dashboard/hackathons" style={{ color: "#58a6ff" }}>← Back to hackathons</Link></div>;
  const timeline = [["Registration", hackathon.registration], ["Starts", hackathon.start], ["Ends", hackathon.end]];

  return <div className="github-dashboard" style={{ color: "#e6edf3" }}>
    <Link href="/dashboard/hackathons" style={{ display: "inline-block", marginBottom: 20, color: "#8b949e", fontSize: 13, textDecoration: "none" }}>← All hackathons</Link>
    <section style={{ marginBottom: 20, padding: "clamp(24px, 5vw, 48px)", border: "1px solid #30363d", borderRadius: 6, background: "linear-gradient(120deg, #161b22 0%, #102846 100%)" }}><p style={{ margin: 0, color: "#58a6ff", fontSize: 12, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase" }}>{hackathon.platform} · {hackathon.format}{hackathon.location ? ` · ${hackathon.location}` : ""}</p><h1 style={{ maxWidth: 760, margin: "12px 0", fontSize: "clamp(30px, 5vw, 52px)", lineHeight: 1.05, letterSpacing: "-.04em" }}>{hackathon.name}</h1><p style={{ maxWidth: 720, margin: 0, color: "#c9d1d9", fontSize: 16, lineHeight: 1.6 }}>{hackathon.description}</p><div style={{ display: "flex", flexWrap: "wrap", gap: 10, marginTop: 24 }}><button type="button" onClick={() => setMatchingOpen(true)} style={{ padding: "8px 12px", border: "1px solid #30363d", borderRadius: 6, background: "#21262d", color: "#e6edf3", fontWeight: 600, cursor: "pointer" }}>Find Teammates</button><a href={hackathon.link} target="_blank" rel="noreferrer" style={{ padding: "8px 12px", border: "1px solid rgba(240,246,252,.12)", borderRadius: 6, background: "#238636", color: "white", fontSize: 14, fontWeight: 600, textDecoration: "none" }}>Join Hackathon ↗</a></div></section>
    <div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1.4fr) minmax(250px, .6fr)", gap: 20 }}><section style={{ padding: 20, border: "1px solid #30363d", borderRadius: 6, background: "#161b22" }}><h2 style={{ margin: "0 0 12px", fontSize: 17 }}>About this hackathon</h2><p style={{ margin: 0, color: "#8b949e", lineHeight: 1.65 }}>{hackathon.description} Visit the official event page for eligibility, submission requirements, and the latest schedule updates.</p><h2 style={{ margin: "28px 0 12px", fontSize: 17 }}>Themes</h2><div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>{hackathon.themes.map((theme) => <span key={theme} style={{ padding: "5px 9px", border: "1px solid #30363d", borderRadius: 999, background: "#21262d", color: "#e6edf3", fontSize: 12 }}>{theme}</span>)}</div></section><aside style={{ display: "grid", gap: 16, alignContent: "start" }}><section style={{ padding: 20, border: "1px solid #30363d", borderRadius: 6, background: "#161b22" }}><span style={{ color: "#8b949e", fontSize: 12 }}>Prize pool</span><strong style={{ display: "block", marginTop: 6, color: "#3fb950", fontSize: 32, letterSpacing: "-.04em" }}>{hackathon.prize}</strong></section><section style={{ padding: 20, border: "1px solid #30363d", borderRadius: 6, background: "#161b22" }}><h2 style={{ margin: "0 0 14px", fontSize: 15 }}>Timeline</h2>{timeline.map(([label, date]) => <div key={label} style={{ display: "grid", gridTemplateColumns: "90px 1fr", gap: 10, padding: "10px 0", borderTop: "1px solid #30363d", fontSize: 13 }}><span style={{ color: "#8b949e" }}>{label}</span><span>{date}</span></div>)}</section></aside></div>
    {matchingOpen && <div role="dialog" aria-modal="true" aria-labelledby="matching-title" style={{ position: "fixed", inset: 0, zIndex: 80, display: "grid", placeItems: "center", padding: 20, background: "rgba(1,4,9,.78)" }}><div style={{ width: "min(100%, 430px)", padding: 22, border: "1px solid #30363d", borderRadius: 6, background: "#161b22", boxShadow: "0 16px 48px rgba(1,4,9,.75)" }}><h2 id="matching-title" style={{ margin: 0, fontSize: 18 }}>AI Team Matching</h2><p style={{ margin: "10px 0 18px", color: "#8b949e", fontSize: 13, lineHeight: 1.55 }}>Choose one of your projects to use its skills and requirements when matching with available CoSkill builders.</p><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}><button type="button" onClick={() => setMatchingOpen(false)} style={{ padding: "7px 10px", border: "1px solid #30363d", borderRadius: 6, background: "#21262d", color: "#e6edf3", cursor: "pointer" }}>Cancel</button><Link href="/dashboard/projects" style={{ padding: "7px 10px", borderRadius: 6, background: "#2f81f7", color: "white", fontSize: 13, fontWeight: 600, textDecoration: "none" }}>Choose a project</Link></div></div></div>}
  </div>;
}
